### ISSUE TITLE
"&" character isn't managed into folder for local filesystem's URL

### ISSUE THREAD

**Issue by Youtch** [hanya/BookmarksMenu#9]
I meet an unexpected behavior when I want to add this bookmark  : 

> C:\Users\Gardien\Documents\Travail\_Technique,tutos & co\Les étape du prototypage.odt

 ... I receive popup window informing me:

>  C:\Users\Gardien\Documents\Travail\_Technique,tutos  n'existe pas (English translation : [URL] doesn't exist)

I deduct that the "&" character isn't managed into an URL ! 
To confirm that, firstly I tryed to change folder name to "_technique" and that works. 
Secondly I tryed to change the folder for "&" and that doesn't work.
It would be good to fix it.
Regards.

**Comment by Koala** [comment]
Oh, I'm not alone with this problem. The same problem by me at Work with Windows and OpenOffice and at home with Linux and Libre Office.
In Linux my test path is: "/ramdisc/test & test2".
I will open a file via bookmark. The error message is: "/ramdisc/test  does not exist.", I press "OK" and the same message pop up twice. Press "OK" and I see: "Object not accessible.
The object cannot be accessed due to insufficient user rights."
User rights are not the problem, I create the file 1 minute befor :-)

At home on my Linux system I never use the "&" sign in a path. But at Work the path was created long time ago in a network share by a Windows only user :-(

Edit the bookmarks:
In the path for the document I see this: file:///ramdisc/test%20&%20test2/testtest%20&%20test.odt

**Comment by hanya** [comment]
Fixed on version 1.0.15.

As a record of the problem, the reson of this problem was there in the office. 
If the .uno:Open command is passed to the frame dispatcher, it converts URL twice or more. 
So the ampersand will be contained in the URL before execution of the command. It will be split as part of parameters.
The URL inserted in the menubar or toolbars should be escaped twice, so that it can keep valid URL. 
The ampersand should be %2526. It will be unescaped %26 first and then &. %25 is unescaped as %.

If you dispatch the same URL through dispatch helper or other dispatch framework, it won't be the same.
